# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
branches:
    only:
        - Rpackagev2

language: r
sudo: false
cache: packages
latex: false

r_packages:
    - covr
    - devtools

warnings_are_errors: false

notifications:
    email:
        on_success: change
        on_failure: always

after_success:
    - Rscript -e 'covr::codecov(type = "all")'
