codecov:
  token: 3462bda5-e9f0-4bef-9857-b460457fde4e

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
